import type {
  ClassRoom,
  Area,
  Schedule,
  Inspection,
  InspectionItem,
  ViolationType,
  PenaltyRule,
  Violation,
  Penalty,
  InventoryItem,
  InventoryLog,
  TeacherClassAssignment,
} from '../types';

// ============================================================
// PRODUCTION MASTER TEMPLATES (STRICTLY CLEAN, NO MOCK/DEMO UIDs)
// ============================================================
export const PRODUCTION_MASTER_CLASSES: ClassRoom[] = [
  {
    id: 'class-1',
    name: 'X IPA 1',
    grade: '10',
    building: 'Gedung Umar bin Khattab',
    isActive: true,
    createdAt: '2026-08-01T08:00:00Z',
    updatedAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'class-2',
    name: 'X IPA 2',
    grade: '10',
    building: 'Gedung Umar bin Khattab',
    isActive: true,
    createdAt: '2026-08-01T08:00:00Z',
    updatedAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'class-3',
    name: 'XI IPA 1',
    grade: '11',
    building: 'Gedung Ali bin Abi Thalib',
    isActive: true,
    createdAt: '2026-08-01T08:00:00Z',
    updatedAt: '2026-08-01T08:00:00Z',
  },
];

// ============================================================
// DEMO / OFFLINE INITIAL DATA (FOR LOCAL PREVIEW / TESTING ONLY)
// ============================================================
export const INITIAL_CLASSES: ClassRoom[] = [
  {
    id: 'class-1',
    name: 'X IPA 1',
    grade: '10',
    building: 'Gedung Umar bin Khattab',
    homeroomTeacherId: 'demo-teacher-uid',
    homeroomTeacherName: 'Ustadz Syarif Hidayatullah',
    isActive: true,
    createdAt: '2026-08-01T08:00:00Z',
    updatedAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'class-2',
    name: 'X IPA 2',
    grade: '10',
    building: 'Gedung Umar bin Khattab',
    homeroomTeacherId: 'teacher-2',
    homeroomTeacherName: 'Ustadzah Nurul Latifah',
    isActive: true,
    createdAt: '2026-08-01T08:00:00Z',
    updatedAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'class-3',
    name: 'XI IPA 1',
    grade: '11',
    building: 'Gedung Ali bin Abi Thalib',
    homeroomTeacherId: 'teacher-3',
    homeroomTeacherName: 'Ustadz Abdullah Hakim',
    isActive: true,
    createdAt: '2026-08-01T08:00:00Z',
    updatedAt: '2026-08-01T08:00:00Z',
  },
];

export const INITIAL_AREAS: Area[] = [
  {
    id: 'area-1',
    name: 'Ruang Kelas X IPA 1',
    category: 'class',
    classId: 'class-1',
    building: 'Gedung Umar bin Khattab',
    floor: 1,
    description: 'Kapasitas 32 santri, ber-AC',
    isActive: true,
    createdAt: '2026-08-01T08:00:00Z',
    updatedAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'area-2',
    name: 'Ruang Kelas X IPA 2',
    category: 'class',
    classId: 'class-2',
    building: 'Gedung Umar bin Khattab',
    floor: 1,
    description: 'Kapasitas 30 santri',
    isActive: true,
    createdAt: '2026-08-01T08:00:00Z',
    updatedAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'area-3',
    name: 'Toilet Santri Putra Lt 1',
    category: 'bathroom',
    building: 'Gedung Umar bin Khattab',
    floor: 1,
    description: '6 bilik toilet + 4 tempat wudhu',
    isActive: true,
    createdAt: '2026-08-01T08:00:00Z',
    updatedAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'area-4',
    name: 'Koridor Utama Lantai 1',
    category: 'hallway',
    building: 'Gedung Umar bin Khattab',
    floor: 1,
    description: 'Akses lalu lintas utama santri',
    isActive: true,
    createdAt: '2026-08-01T08:00:00Z',
    updatedAt: '2026-08-01T08:00:00Z',
  },
];

export const INITIAL_SCHEDULES: Schedule[] = [
  {
    id: 'sched-1',
    areaId: 'area-1',
    areaName: 'Ruang Kelas X IPA 1',
    assignedCleanerId: 'demo-cleaner-uid',
    assignedCleanerName: 'Pak Slamet (Tim Kebersihan)',
    frequency: 'daily',
    timeSlot: '06:30 - 07:00',
    daysOfWeek: [1, 2, 3, 4, 5, 6],
    isActive: true,
    createdAt: '2026-08-01T08:00:00Z',
    updatedAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'sched-2',
    areaId: 'area-3',
    areaName: 'Toilet Santri Putra Lt 1',
    assignedCleanerId: 'demo-cleaner-uid',
    assignedCleanerName: 'Pak Slamet (Tim Kebersihan)',
    frequency: 'daily',
    timeSlot: '11:30 - 12:00',
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    isActive: true,
    createdAt: '2026-08-01T08:00:00Z',
    updatedAt: '2026-08-01T08:00:00Z',
  },
];

export const INITIAL_VIOLATION_TYPES: ViolationType[] = [
  {
    id: 'vt-1',
    name: 'Sampah Menumpuk Tidak Dibuang',
    description: 'Tong sampah di dalam kelas penuh meluber atau sampah berserakan di kolong meja',
    severity: 'medium',
    defaultPenaltyAmount: 25000,
    isActive: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'vt-2',
    name: 'Coretan Meja / Dinding',
    description: 'Vandalisme berupa tulisan/coretan di perabot atau dinding kelas',
    severity: 'high',
    defaultPenaltyAmount: 50000,
    isActive: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'vt-3',
    name: 'Papan Tulis Belum Dihapus',
    description: 'Papan tulis dibiarkan kotor setelah kegiatan belajar usai',
    severity: 'low',
    defaultPenaltyAmount: 10000,
    isActive: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'vt-4',
    name: 'Lantai Kotor / Noda Minuman',
    description: 'Lantai becek, tumpahan sirup/kopi tidak dibersihkan piket kelas',
    severity: 'medium',
    defaultPenaltyAmount: 20000,
    isActive: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
];

export const INITIAL_PENALTY_RULES: PenaltyRule[] = [
  {
    id: 'pr-1',
    violationTypeId: 'vt-1',
    violationTypeName: 'Sampah Menumpuk Tidak Dibuang',
    minOccurrences: 1,
    fineAmount: 25000,
    description: 'Peringatan pertama & denda kas piket kebersihan',
    isActive: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'pr-2',
    violationTypeId: 'vt-2',
    violationTypeName: 'Coretan Meja / Dinding',
    minOccurrences: 1,
    fineAmount: 50000,
    description: 'Wajib membersihkan cat dan denda material pembersih',
    isActive: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
];

export const INITIAL_INSPECTIONS: Inspection[] = [
  {
    id: 'insp-101',
    areaId: 'area-1',
    areaName: 'Ruang Kelas X IPA 1',
    classId: 'class-1',
    inspectorId: 'demo-cleaner-uid',
    inspectorName: 'Pak Slamet (Tim Kebersihan)',
    date: '2026-08-27',
    status: 'completed',
    overallGrade: 'dirty',
    totalScore: 68,
    notes: 'Ditemukan sampah sisa makanan di kolong meja deret 3 dan papan tulis kotor.',
    hasViolations: true,
    completedAt: '2026-08-27T07:15:00Z',
    createdAt: '2026-08-27T06:50:00Z',
    updatedAt: '2026-08-27T07:15:00Z',
  },
  {
    id: 'insp-102',
    areaId: 'area-2',
    areaName: 'Ruang Kelas X IPA 2',
    classId: 'class-2',
    inspectorId: 'demo-cleaner-uid',
    inspectorName: 'Pak Slamet (Tim Kebersihan)',
    date: '2026-08-27',
    status: 'completed',
    overallGrade: 'clean',
    totalScore: 95,
    notes: 'Kondisi rapi, meja tertata bersih, tempat sampah kosong berplastik.',
    hasViolations: false,
    completedAt: '2026-08-27T07:35:00Z',
    createdAt: '2026-08-27T07:20:00Z',
    updatedAt: '2026-08-27T07:35:00Z',
  },
];

export const INITIAL_INSPECTION_ITEMS: InspectionItem[] = [
  {
    id: 'ii-1',
    inspectionId: 'insp-101',
    itemName: 'Kebersihan Lantai',
    passed: true,
    score: 85,
    notes: 'Sudah disapu namun ada sedikit debu di sudut',
    createdAt: '2026-08-27T07:00:00Z',
  },
  {
    id: 'ii-2',
    inspectionId: 'insp-101',
    itemName: 'Kolong Meja & Kursi',
    passed: false,
    score: 40,
    notes: 'Banyak bungkus snack dan botol plastik kosong',
    createdAt: '2026-08-27T07:05:00Z',
  },
  {
    id: 'ii-3',
    inspectionId: 'insp-101',
    itemName: 'Papan Tulis & Penghapus',
    passed: false,
    score: 50,
    notes: 'Bekas materi kemarin sore belum dihapus',
    createdAt: '2026-08-27T07:07:00Z',
  },
  {
    id: 'ii-4',
    inspectionId: 'insp-101',
    itemName: 'Tempat Sampah',
    passed: true,
    score: 90,
    notes: 'Plastik sampah terpasang rapi',
    createdAt: '2026-08-27T07:10:00Z',
  },
];

export const INITIAL_VIOLATIONS: Violation[] = [
  {
    id: 'viol-1',
    inspectionId: 'insp-101',
    areaId: 'area-1',
    areaName: 'Ruang Kelas X IPA 1',
    classId: 'class-1',
    className: 'X IPA 1',
    violationTypeId: 'vt-1',
    violationTypeName: 'Sampah Menumpuk Tidak Dibuang',
    severity: 'medium',
    description: 'Sampah bungkus makanan berserakan di kolong meja baris 3 & 4',
    reportedById: 'demo-cleaner-uid',
    reportedByName: 'Pak Slamet (Tim Kebersihan)',
    date: '2026-08-27',
    photoUrls: ['https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80'],
    penaltyCreated: true,
    createdAt: '2026-08-27T07:12:00Z',
    updatedAt: '2026-08-27T07:12:00Z',
  },
];

export const INITIAL_PENALTIES: Penalty[] = [
  {
    id: 'pen-1',
    violationId: 'viol-1',
    classId: 'class-1',
    className: 'X IPA 1',
    responsiblePerson: 'Ketua Piket Kelas X IPA 1',
    amount: 25000,
    reason: 'Sampah bungkus makanan menumpuk di kolong meja saat jam inspeksi pagi',
    status: 'pending',
    issuedById: 'demo-cleaner-uid',
    issuedByName: 'Pak Slamet (Tim Kebersihan)',
    issuedDate: '2026-08-27',
    notes: 'Denda diserahkan ke kas kebersihan pondok maksimal 2 hari kerja.',
    createdAt: '2026-08-27T07:14:00Z',
    updatedAt: '2026-08-27T07:14:00Z',
  },
];

export const INITIAL_INVENTORIES: InventoryItem[] = [
  {
    id: 'inv-1',
    name: 'Sapu Lantai Ijuk Standar',
    category: 'tool',
    stock: 24,
    unit: 'buah',
    condition: 'good',
    location: 'Gudang Utama Lt 1',
    minStockAlert: 5,
    lastRestockedAt: '2026-08-15T10:00:00Z',
    createdAt: '2026-08-01T08:00:00Z',
    updatedAt: '2026-08-15T10:00:00Z',
  },
  {
    id: 'inv-2',
    name: 'Alat Pel Jepit Microfiber',
    category: 'tool',
    stock: 12,
    unit: 'buah',
    condition: 'good',
    location: 'Gudang Utama Lt 1',
    minStockAlert: 4,
    lastRestockedAt: '2026-08-15T10:00:00Z',
    createdAt: '2026-08-01T08:00:00Z',
    updatedAt: '2026-08-15T10:00:00Z',
  },
  {
    id: 'inv-3',
    name: 'Cairan Karbol Pembersih Wangi Pinus',
    category: 'chemical',
    stock: 6,
    unit: 'jerigen (5L)',
    condition: 'good',
    location: 'Gudang Kimia Lt 1',
    minStockAlert: 2,
    lastRestockedAt: '2026-08-20T14:00:00Z',
    createdAt: '2026-08-01T08:00:00Z',
    updatedAt: '2026-08-20T14:00:00Z',
  },
  {
    id: 'inv-4',
    name: 'Plastik Sampah Hitam Roll Jumbo',
    category: 'consumable',
    stock: 3,
    unit: 'pack',
    condition: 'needs_replacement',
    location: 'Gudang Utama Lt 1',
    minStockAlert: 5,
    lastRestockedAt: '2026-08-10T09:00:00Z',
    createdAt: '2026-08-01T08:00:00Z',
    updatedAt: '2026-08-26T16:00:00Z',
  },
];

export const INITIAL_INVENTORY_LOGS: InventoryLog[] = [
  {
    id: 'log-1',
    inventoryId: 'inv-3',
    inventoryName: 'Cairan Karbol Pembersih Wangi Pinus',
    action: 'restock',
    quantityChanged: 5,
    previousStock: 1,
    newStock: 6,
    performedById: 'demo-cleaner-uid',
    performedByName: 'Pak Slamet (Tim Kebersihan)',
    notes: 'Pengadaan mingguan dari koperasi pesantren',
    createdAt: '2026-08-20T14:00:00Z',
  },
  {
    id: 'log-2',
    inventoryId: 'inv-4',
    inventoryName: 'Plastik Sampah Hitam Roll Jumbo',
    action: 'use',
    quantityChanged: -2,
    previousStock: 5,
    newStock: 3,
    performedById: 'demo-cleaner-uid',
    performedByName: 'Pak Slamet (Tim Kebersihan)',
    notes: 'Distribusi ke tong sampah Gedung Umar',
    createdAt: '2026-08-26T16:00:00Z',
  },
];

export const INITIAL_TEACHER_ASSIGNMENTS: TeacherClassAssignment[] = [
  {
    id: 'assign-1',
    teacherId: 'demo-teacher-uid',
    teacherName: 'Ustadz Syarif Hidayatullah',
    classId: 'class-1',
    className: 'X IPA 1',
    academicYear: '2026/2027',
    assignedAt: '2026-08-01T08:00:00Z',
  },
];
